# Generated by Django 2.2.4 on 2019-08-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
