# Generated by Django 2.2.2 on 2019-06-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('SL', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=30)),
                ('Student_ID', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.CharField(max_length=3)),
                ('SL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Details')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Student')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='Student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Student'),
        ),
    ]
