# Generated by Django 2.2.2 on 2019-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='url',
            field=models.URLField(default='Something', unique=True),
        ),
    ]
