# Generated by Django 2.2.4 on 2019-08-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_imagepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='title',
        ),
    ]
