# Generated by Django 2.2.4 on 2019-08-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190810_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
