# Generated by Django 2.2.4 on 2019-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
