# Generated by Django 2.2.4 on 2019-08-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
