# Generated by Django 2.2.4 on 2019-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='cover',
            field=models.FileField(blank=True, upload_to='media/images/'),
        ),
    ]
