# Generated by Django 2.2.4 on 2019-08-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190813_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
