# Generated by Django 2.2.4 on 2019-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190813_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
