# Generated by Django 2.2.4 on 2019-08-13 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_imagepost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
